.TH "__input_section__" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__input_section__ \- 
.PP
Input data type (user-defined\&.)
.PP
This class provides an interface slot for data to be input and parsed by components of the library\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/impl-defined\&.hpp>\fP
.SH "Detailed Description"
.PP 

.PP
\fBAttention:\fP
.RS 4
To define this class, remove the __ from before and after\&. They are added for the purposes of differentiation between the class concept and the definition(s) provided by the library for optional use\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBclasses/string-input\&.hpp\fP provides a simple definition\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
