.TH "hparser Directory Reference" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hparser Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBaux\fP"
.br
.ti -1c
.RI "directory \fBclasses\fP"
.br
.ti -1c
.RI "directory \fBformats\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcomm-line\&.hpp\fP"
.br
.ti -1c
.RI "file \fBconnection-control\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdata-input\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdata-manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdata-output\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfile-input\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfile-manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfile-output\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfile-user\&.hpp\fP"
.br
.ti -1c
.RI "file \fBimpl-defined\&.hpp\fP"
.br
.ti -1c
.RI "file \fBinput-control\&.hpp\fP"
.br
.ti -1c
.RI "file \fBinput-manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBinput-resource\&.hpp\fP"
.br
.ti -1c
.RI "file \fBinterface-user\&.hpp\fP"
.br
.ti -1c
.RI "file \fBlinked-section\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmulti-destination\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmulti-input\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmulti-output\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmulti-source\&.hpp\fP"
.br
.ti -1c
.RI "file \fBoperators\&.hpp\fP"
.br
.ti -1c
.RI "file \fBoutput-control\&.hpp\fP"
.br
.ti -1c
.RI "file \fBoutput-manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBoutput-resource\&.hpp\fP"
.br
.ti -1c
.RI "file \fBparent-storage\&.hpp\fP"
.br
.ti -1c
.RI "file \fBscope-locator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstorage-section\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstructure-base\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtriggered-update\&.hpp\fP"
.br
.ti -1c
.RI "file \fBverified-element\&.hpp\fP"
.br
.ti -1c
.RI "file \fBversion\&.hpp\fP"
.br
.in -1c
