.TH "hparser/aux Directory Reference" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hparser/aux Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgeneric-file\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstandard-error\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstandard-input\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstandard-output\&.hpp\fP"
.br
.in -1c
