.TH "hparser/formats Directory Reference" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hparser/formats Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdescriptor-input\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdescriptor-output\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdescriptor-storage\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmanaged-input\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmanaged-output\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtag-constants\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtag-properties\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtagged-input\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtagged-output\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtagged-storage\&.hpp\fP"
.br
.in -1c
