.TH "bin_file" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin_file \- 
.PP
Binary input/output file interface\&.
.PP
This class implements the open_file function of \fBgeneric_file\fP to open files in binary mode\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/aux/generic-file\&.hpp>\fP
.SS "Public Member Functions"

.PP
.RI "\fBImplemented from file_user\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "bool \fBopen_file\fP (bool, bool)"
.br
.in -1c
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "bool bin_file::open_file (bool, bool)\fC [virtual]\fP"
Open the current file\&. 
.PP
Implements \fBfile_user\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
