.TH "data_manager" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_manager \- 
.PP
Combined input/output manager\&.
.PP
This is a convenience class for implementing both \fBinput_manager\fP and \fBoutput_manager\fP in the same object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/data-manager\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
