.TH "descriptor_storage" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
descriptor_storage \- 
.PP
Combined descriptor input/output\&.
.PP
This is a convenience class for implementing both \fBdescriptor_input\fP and \fBdescriptor_output\fP in the same object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/formats/descriptor-storage\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
