.TH "file_input" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_input \- 
.PP
File input source\&.
.PP
This is a convenience class for implementing both \fBdata_input\fP and \fBfile_user\fP in the same object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/file-input\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
