.TH "file_output" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_output \- 
.PP
File output destination\&.
.PP
This is a convenience class for implementing both \fBdata_output\fP and \fBfile_user\fP in the same object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/file-output\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
