.TH "Optional Class Definitions" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Optional Class Definitions \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBscope_identifier\fP"
.br
.RI "\fIFILO implementation of scope identifers\&.
.PP
This is an optional class definition for \fBscope_identifier\fP\&. This class may be defined by the user instead of using this definition\&. Make sure to include the same class definition in all communicating units of your program! This definition treats the identifier as a stack of scopes\&. Layers are added and removed from the bottom and comparison to a reference layer is done with the bottom layer\&. This class is derived from std::deque\&. \fP"
.ti -1c
.RI "class \fBcomposite_data\fP"
.br
.RI "\fIString implementation of composite data\&.
.PP
This is an optional class definition for \fBcomposite_data\fP\&. This class may be defined by the user instead of using this definition\&. Make sure to include the same class definition in all communicating units of your program! All functions here mirror std::string\&. \fP"
.ti -1c
.RI "class \fBinput_section\fP"
.br
.RI "\fIString implementation of input data\&.
.PP
This is an optional class definition for \fBinput_section\fP\&. This class may be defined by the user instead of using this definition\&. Make sure to include the same class definition in all communicating units of your program! All functions here mirror std::string\&. \fP"
.ti -1c
.RI "class \fBcomm_message\fP"
.br
.RI "\fIString implementation of messages\&.
.PP
This is an optional class definition for \fBcomm_message\fP\&. This class may be defined by the user instead of using this definition\&. Make sure to include the same class definition in all communicating units of your program! All functions here mirror std::string\&. \fP"
.ti -1c
.RI "class \fBoutput_section\fP"
.br
.RI "\fIString implementation of output data\&.
.PP
This is an optional class definition for \fBoutput_section\fP\&. This class may be defined by the user instead of using this definition\&. Make sure to include the same class definition in all communicating units of your program! All functions here mirror std::string\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBSee also:\fP
.RS 4
\fBImplementation-defined Classes\fP provides an explanation of the implementation-defined concept\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
