.TH "input_control" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_control \- 
.PP
Data input recursion control\&.
.PP
This class provides recursion control to input interface classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/input-control\&.hpp>\fP
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBsection_open\fP () const "
.br
.ti -1c
.RI "virtual bool \fBset_section_open\fP (bool)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual bool input_control::section_open () const\fC [protected]\fP, \fC [virtual]\fP"
Determine if the input section is open for input\&. 
.SS "virtual bool input_control::set_section_open (bool)\fC [protected]\fP, \fC [virtual]\fP"
Change the section's open status\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
