.TH "input_section" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_section \- 
.PP
String implementation of input data\&.
.PP
This is an optional class definition for \fBinput_section\fP\&. This class may be defined by the user instead of using this definition\&. Make sure to include the same class definition in all communicating units of your program! All functions here mirror std::string\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/classes/string-input\&.hpp>\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
