.TH "interface_user" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interface_user \- 
.PP
Parallel interface user\&.
.PP
This class provides an interface to a parallel structural interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/interface-user\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual element_interface * \fBextract_interface\fP ()"
.br
.ti -1c
.RI "virtual const element_interface * \fBextract_interface\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAttention:\fP
.RS 4
This class uses the element_interface class which is entirely implementation-defined by the using program\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual element_interface* interface_user::extract_interface ()\fC [virtual]\fP"
Extract the interface\&. 
.SS "virtual const element_interface* interface_user::extract_interface () const\fC [virtual]\fP"
Extract the interface\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
