.TH "Memory Management" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory Management \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsection_releaser\fP"
.br
.RI "\fIConsumable memory management wrapper\&.
.PP
This class is a wrapper for dynamic pointer returns from \fBstorage_section\fP functions\&. This is the primary memory management class for elements not currently owned by another element\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
