.TH "multi_destination" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multi_destination \- 
.PP
Multiple-destination data output\&.
.PP
This class serves as an output source selector\&. The deriving class will generally have more than one \fBdata_output\fP built in and will select one of the destinations for a particular input operation based on that class' own criteria\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/multi-destination\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
