.TH "multi_output" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multi_output \- 
.PP
Interchangable output interface\&.
.PP
This class provides an abstract interface for objects with interchangable output interfaces\&. The means of interface changing is up to the derived class\&. This class polls an abstract function for the current interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/multi-output\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
