.TH "multi_source" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multi_source \- 
.PP
Multiple-source data input\&.
.PP
This class serves as an input source selector\&. The deriving class will generally have more than one \fBdata_input\fP built in and will select one of the sources for a particular input operation based on that class' own criteria\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/multi-source\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
