.TH "Random-access Resources" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Random-access Resources \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBinput_resource\fP"
.br
.RI "\fIRandom-access input resource\&.
.PP
This class provides a random-access input interface\&. \fP"
.ti -1c
.RI "class \fBinput_resource_owner\fP"
.br
.RI "\fIRandom-access input resource owner\&.
.PP
This class provides an interface for providing an input resource\&. \fP"
.ti -1c
.RI "class \fBoutput_resource\fP"
.br
.RI "\fIRandom-access output resource\&.
.PP
This class provides a random-access output interface\&. \fP"
.ti -1c
.RI "class \fBoutput_resource_owner\fP"
.br
.RI "\fIRandom-access output resource owner\&.
.PP
This class provides an interface for providing an output resource\&. \fP"
.ti -1c
.RI "class \fBscope_locator\fP"
.br
.RI "\fIScope-controllable object\&.
.PP
This class provides basic functionality to manage parsing scopes for a hierarchy\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
