.TH "standard_error" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
standard_error \- 
.PP
Standard error interface\&.
.PP
This class is not yet written!  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/aux/standard-error\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
