.TH "tagged_storage" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagged_storage \- 
.PP
Combined tagged input/output\&.
.PP
This is a convenience class for implementing both \fBtagged_input\fP and \fBtagged_output\fP in the same object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/formats/tagged-storage\&.hpp>\fP
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
