.TH "User-intended Classes" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User-intended Classes \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbin_file\fP"
.br
.RI "\fIBinary input/output file interface\&.
.PP
This class implements the open_file function of \fBgeneric_file\fP to open files in binary mode\&. \fP"
.ti -1c
.RI "class \fBstandard_error\fP"
.br
.RI "\fIStandard error interface\&.
.PP
This class is not yet written! \fP"
.ti -1c
.RI "class \fBstandard_input\fP"
.br
.RI "\fIStandard input interface\&.
.PP
This class is not yet written! \fP"
.ti -1c
.RI "class \fBstandard_output\fP"
.br
.RI "\fIStandard output interface\&.
.PP
This class is not yet written! \fP"
.ti -1c
.RI "class \fBdata_manager\fP"
.br
.RI "\fICombined input/output manager\&.
.PP
This is a convenience class for implementing both \fBinput_manager\fP and \fBoutput_manager\fP in the same object\&. \fP"
.ti -1c
.RI "class \fBdescriptor_input\fP"
.br
.RI "\fIInput interface for descriptor-formated sections\&.
.PP
This class provides a simple interface for parsing data that uses a descriptor-style format (where each section's header contains all information pertaining to the section's size\&.) This interface must be combined virtually with an element class in order to be useful\&. \fP"
.ti -1c
.RI "class \fBdescriptor_output\fP"
.br
.RI "\fIOutput interface for descriptor-formated sections\&.
.PP
This class provides a simple interface for exporting data that uses a descriptor-style format (where each section's header contains all information pertaining to the section's size\&.) This interface must be combined virtually with an element class in order to be useful\&. \fP"
.ti -1c
.RI "class \fBdescriptor_storage\fP"
.br
.RI "\fICombined descriptor input/output\&.
.PP
This is a convenience class for implementing both \fBdescriptor_input\fP and \fBdescriptor_output\fP in the same object\&. \fP"
.ti -1c
.RI "class \fBmanaged_input\fP"
.br
.RI "\fICommon formatted-input functions\&.
.PP
This class provides the basic functions required for format classes to automatically parse input\&. This is the minimum interface required by all format classes provided\&. \fP"
.ti -1c
.RI "class \fBmanaged_ouput\fP"
.br
.RI "\fICommon formatted-output functions\&.
.PP
This class provides the basic functions required for format classes to automatically export output\&. This is the minimum interface required by all format classes provided\&. \fP"
.ti -1c
.RI "class \fBtagged_input\fP"
.br
.RI "\fIInput interface for tag-formated sections\&.
.PP
This class provides a simple interface for parsing data that uses a tagged (e\&.g\&. XML) format\&. This interface must be combined virtually with an element class in order to be useful\&. \fP"
.ti -1c
.RI "class \fBtagged_output\fP"
.br
.RI "\fIOutput interface for tag-formated sections\&.
.PP
This class provides a simple interface for exporting data that uses a tagged (e\&.g\&. XML) format\&. This interface must be combined virtually with an element class in order to be useful\&. \fP"
.ti -1c
.RI "class \fBtagged_storage\fP"
.br
.RI "\fICombined tagged input/output\&.
.PP
This is a convenience class for implementing both \fBtagged_input\fP and \fBtagged_output\fP in the same object\&. \fP"
.ti -1c
.RI "class \fBinput_manager\fP"
.br
.RI "\fIAutomatic data importer\&.
.PP
This class automates input of data for construction of a tree\&. \fP"
.ti -1c
.RI "class \fBinput_resource\fP"
.br
.RI "\fIRandom-access input resource\&.
.PP
This class provides a random-access input interface\&. \fP"
.ti -1c
.RI "class \fBinput_resource_owner\fP"
.br
.RI "\fIRandom-access input resource owner\&.
.PP
This class provides an interface for providing an input resource\&. \fP"
.ti -1c
.RI "class \fBlinked_section\fP"
.br
.RI "\fIPartially-abstract tree element class\&.
.PP
This class provides linking functionality for \fBstorage_section\fP\&. This class owns the element following it and its first child element\&. This means that upon its own deletion it deletes its child elements and the following element if this element has no owner itself\&. Some functions are overridden or implemented with specific functionality unique to a linked element\&. \fP"
.ti -1c
.RI "class \fBmulti_input\fP"
.br
.RI "\fIInterchangable input interface\&.
.PP
This class provides an abstract interface for objects with interchangable input interfaces\&. The means of interface changing is up to the derived class\&. This class polls an abstract function for the current interface\&. \fP"
.ti -1c
.RI "class \fBmulti_output\fP"
.br
.RI "\fIInterchangable output interface\&.
.PP
This class provides an abstract interface for objects with interchangable output interfaces\&. The means of interface changing is up to the derived class\&. This class polls an abstract function for the current interface\&. \fP"
.ti -1c
.RI "class \fBoutput_manager\fP"
.br
.RI "\fIAutomatic data exporter\&.
.PP
This class automates output of data from a tree\&. \fP"
.ti -1c
.RI "class \fBoutput_resource\fP"
.br
.RI "\fIRandom-access output resource\&.
.PP
This class provides a random-access output interface\&. \fP"
.ti -1c
.RI "class \fBoutput_resource_owner\fP"
.br
.RI "\fIRandom-access output resource owner\&.
.PP
This class provides an interface for providing an output resource\&. \fP"
.ti -1c
.RI "class \fBstructure_base\fP"
.br
.RI "\fIHierarchy base container\&.
.PP
This class serves as a simple base object for a hierarchy\&. It is the parent of the base element of the tree, and is therefore the base of the tree\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
