.TH "verified_element" 3 "Fri Dec 5 2014" "Version hparser-1.0.0" "hparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
verified_element \- 
.PP
Prevents circular ownership\&.
.PP
This class is used to enumerate hierarchies to make pre-insertion checking more reliable\&. Elements are checked against their insertion points to make sure the insertion points aren't indirectly owned by the element being inserted\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hparser/verified-element\&.hpp>\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for hparser from the source code\&.
